name: Deploy

on:
  workflow_dispatch: 
  push:
    branches:
      - pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/UnKabaraQuiDev

            git fetch origin
            git checkout pages
            git reset --hard origin/pages
